***** Create Labels *****;
LABEL CLASS_PROB1 = 'Setosa    ' CLASS_PROB2 = 'Versicolou' CLASS_PROB3 = 
'Virginica ' ;
***** Create Dummy Variables *****;
***** Main Data Processing *****;
IF PETALLENGTH LE                   19 THEN DO;
    CLASS_PROB1 =                    1;
    CLASS_PROB2 =                    0;
    CLASS_PROB3 =                    0;
END;
ELSE IF PETALLENGTH GT                   19 THEN DO;
    IF PETALWIDTH LE                   17 THEN DO;
        IF PETALLENGTH LE                   49 THEN DO;
            IF PETALWIDTH LE                   16 THEN DO;
                CLASS_PROB1 =                    0;
                CLASS_PROB2 =                    1;
                CLASS_PROB3 =                    0;
            END;
            ELSE IF PETALWIDTH GT                   16 THEN DO;
                CLASS_PROB1 =                    0;
                CLASS_PROB2 =                    0;
                CLASS_PROB3 =                    1;
            END;
        END;
        ELSE IF PETALLENGTH GT                   49 THEN DO;
            IF PETALWIDTH LE                   15 THEN DO;
                CLASS_PROB1 =                    0;
                CLASS_PROB2 =                    0;
                CLASS_PROB3 =                    1;
            END;
            ELSE IF PETALWIDTH GT                   15 THEN DO;
                IF SEPALLENGTH LE                   69 THEN DO;
                    CLASS_PROB1 =                    0;
                    CLASS_PROB2 =                    1;
                    CLASS_PROB3 =                    0;
                END;
                ELSE IF SEPALLENGTH GT                   69 THEN DO;
                    CLASS_PROB1 =                    0;
                    CLASS_PROB2 =                    0;
                    CLASS_PROB3 =                    1;
                END;
            END;
        END;
    END;
    ELSE IF PETALWIDTH GT                   17 THEN DO;
        IF PETALLENGTH LE                   48 THEN DO;
            IF SEPALLENGTH LE                   59 THEN DO;
                CLASS_PROB1 =                    0;
                CLASS_PROB2 =                    1;
                CLASS_PROB3 =                    0;
            END;
            ELSE IF SEPALLENGTH GT                   59 THEN DO;
                CLASS_PROB1 =                    0;
                CLASS_PROB2 =                    0;
                CLASS_PROB3 =                    1;
            END;
        END;
        ELSE IF PETALLENGTH GT                   48 THEN DO;
            CLASS_PROB1 =                    0;
            CLASS_PROB2 =                    0;
            CLASS_PROB3 =                    1;
        END;
    END;
END;
***** Drop Dummy Variables *****;
